pipeline {
    agent any
    stages {
        stage('Install Checkov') {
            steps {
                // Install Checkov using pip
                sh 'pip install checkov'
                sh "pipenv run checkov -d . --use-enforcement-rules -o cli -o junitxml --output-file-path console,results.xml --repo-id realone-repo/kubernetes --branch master"
            }
        }
                    {
        always {
            echo 'Pipeline execution completed.'
        }
        failure {
            echo 'Checkov scan detected issues. Please address the vulnerabilities.'
        }
    }
}
